# Copyright (C) 2015 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

LOCAL_PATH := vendor/huawei/h60-common

PRODUCT_PACKAGES += \
	libion.huawei \
	libGLES_mali

PRODUCT_COPY_FILES := \
    vendor/huawei/h60-common/proprietary/system/ons.bin:system/ons.bin \
    vendor/huawei/h60-common/proprietary/system/lib/libion.huawei.so:system/lib/libion.so \
    vendor/huawei/h60-common/proprietary/system/lib/hw/gralloc.hi3630.so:system/lib/hw/gralloc.hi3630.so \
    vendor/huawei/h60-common/proprietary/system/vendor/lib/hw/hwcomposer.hi3630.so:system/vendor/lib/hw/hwcomposer.hi3630.so \
    vendor/huawei/h60-common/proprietary/system/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so \
    vendor/huawei/h60-common/proprietary/system/vendor/firmware/fw_bcm4334_hw_dualband.bin:system/vendor/firmware/fw_bcm4334_hw_dualband.bin \
    vendor/huawei/h60-common/proprietary/system/vendor/firmware/libpn547_fw.so:system/vendor/firmware/libpn547_fw.so \
    vendor/huawei/h60-common/proprietary/system/vendor/firmware/nvram4334_hw_jazz_clg.txt:system/vendor/firmware/nvram4334_hw_jazz_clg.txt \
    vendor/huawei/h60-common/proprietary/system/vendor/firmware/fw_bcm4334_apsta_hw_dualband.bin:system/vendor/firmware/fw_bcm4334_apsta_hw_dualband.bin \
    vendor/huawei/h60-common/proprietary/system/vendor/firmware/nvram4334_hw_jazz_ulg.txt:system/vendor/firmware/nvram4334_hw_jazz_ulg.txt \
    vendor/huawei/h60-common/proprietary/system/vendor/firmware/nvram4334_hw_mogolia_ulg.txt:system/vendor/firmware/nvram4334_hw_mogolia_ulg.txt \
    vendor/huawei/h60-common/proprietary/system/vendor/firmware/nvram4334_hw_mogolia_tl.txt:system/vendor/firmware/nvram4334_hw_mogolia_tl.txt \
    vendor/huawei/h60-common/proprietary/system/vendor/firmware/nvram4334_hw_mogolia_ulca.txt:system/vendor/firmware/nvram4334_hw_mogolia_ulca.txt \
    vendor/huawei/h60-common/proprietary/system/vendor/firmware/BCM4334B0_002.001.013.1164.1457_RC.hcd:system/vendor/firmware/BCM4334B0_002.001.013.1164.1457_RC.hcd \
    vendor/huawei/h60-common/proprietary/system/vendor/firmware/nvram4334_hw_dualband.txt:system/vendor/firmware/nvram4334_hw_dualband.txt \
    vendor/huawei/h60-common/proprietary/system/vendor/firmware/nvram4334_hw_pine_clg.txt:system/vendor/firmware/nvram4334_hw_pine_clg.txt \
    vendor/huawei/h60-common/proprietary/system/vendor/firmware/nvram4334_hw_pine_tlg.txt:system/vendor/firmware/nvram4334_hw_pine_tlg.txt \
    vendor/huawei/h60-common/proprietary/system/vendor/firmware/nvram4334_hw_jazz_ulca.txt:system/vendor/firmware/nvram4334_hw_jazz_ulca.txt \
    vendor/huawei/h60-common/proprietary/system/vendor/firmware/nvram4334_hw_pine_ulgtlg.txt:system/vendor/firmware/nvram4334_hw_pine_ulgtlg.txt \
    vendor/huawei/h60-common/proprietary/system/vendor/firmware/nvram4334_hw_jazz_tlg.txt:system/vendor/firmware/nvram4334_hw_jazz_tlg.txt \
    vendor/huawei/h60-common/proprietary/system/vendor/firmware/fw_bcm4334_test_hw_apsta_dualband.bin:system/vendor/firmware/fw_bcm4334_test_hw_apsta_dualband.bin \
    vendor/huawei/h60-common/proprietary/system/isp/isp.bin:system/isp/isp.bin \
    vendor/huawei/h60-common/proprietary/system/bin/gpslogd:system/bin/gpslogd \
    vendor/huawei/h60-common/proprietary/system/bin/thermal-daemon:system/bin/thermal-daemon \
    vendor/huawei/h60-common/proprietary/system/bin/gpsdaemon:system/bin/gpsdaemon \
    vendor/huawei/h60-common/proprietary/system/bin/glgps47531cl:system/bin/glgps47531cl \
    vendor/huawei/h60-common/proprietary/system/bin/glgps4752cl:system/bin/glgps4752cl \
    vendor/huawei/h60-common/proprietary/system/bin/atcmdserver:system/bin/atcmdserver \
    vendor/huawei/h60-common/proprietary/system/bin/storedefaultkey:system/bin/storedefaultkey \
    vendor/huawei/h60-common/proprietary/system/bin/hwnffserver:system/bin/hwnffserver \
    vendor/huawei/h60-common/proprietary/system/bin/hw_ueventd:system/bin/hw_ueventd \
    vendor/huawei/h60-common/proprietary/system/bin/hdmi_daemon:system/bin/hdmi_daemon \
    vendor/huawei/h60-common/proprietary/system/bin/hw_cdmamodem_service:system/bin/hw_cdmamodem_service \
    vendor/huawei/h60-common/proprietary/system/bin/glgps47531:system/bin/glgps47531 \
    vendor/huawei/h60-common/proprietary/system/bin/mac_addr_normalization:system/bin/mac_addr_normalization \
    vendor/huawei/h60-common/proprietary/system/bin/glgps4752:system/bin/glgps4752 \
    vendor/huawei/h60-common/proprietary/system/bin/gps4752logd:system/bin/gps4752logd \
    vendor/huawei/h60-common/proprietary/system/bin/device_monitor:system/bin/device_monitor \
    vendor/huawei/h60-common/proprietary/system/bin/hwpged:system/bin/hwpged \
    vendor/huawei/h60-common/proprietary/system/bin/hwnff:system/bin/hwnff \
    vendor/huawei/h60-common/proprietary/system/bin/rild:system/bin/rild \
    vendor/huawei/h60-common/proprietary/system/bin/nvm_server:system/bin/nvm_server \
    vendor/huawei/h60-common/proprietary/system/etc/thermald_performance.xml:system/etc/thermald_performance.xml \
    vendor/huawei/h60-common/proprietary/system/etc/gps4752config_cl.xml:system/etc/gps4752config_cl.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera_resolutions.cfg:system/etc/camera_resolutions.cfg \
    vendor/huawei/h60-common/proprietary/system/etc/modemConfig/SystemCmd.cmf:system/etc/modemConfig/SystemCmd.cmf \
    vendor/huawei/h60-common/proprietary/system/etc/modemConfig/lte_ue_msg.cfg:system/etc/modemConfig/lte_ue_msg.cfg \
    vendor/huawei/h60-common/proprietary/system/etc/modemConfig/viacbp82d_log.bcfg:system/etc/modemConfig/viacbp82d_log.bcfg \
    vendor/huawei/h60-common/proprietary/system/etc/modemConfig/viacbp82d_shutdown_log.bcfg:system/etc/modemConfig/viacbp82d_shutdown_log.bcfg \
    vendor/huawei/h60-common/proprietary/system/etc/camera_config.cfg:system/etc/camera_config.cfg \
    vendor/huawei/h60-common/proprietary/system/etc/srs/srs_processing.cfg:system/etc/srs/srs_processing.cfg \
    vendor/huawei/h60-common/proprietary/system/etc/srs/models.txt:system/etc/srs/models.txt \
    vendor/huawei/h60-common/proprietary/system/etc/srs/srsmodels.lic:system/etc/srs/srsmodels.lic \
    vendor/huawei/h60-common/proprietary/system/etc/gps4752config.xml:system/etc/gps4752config.xml \
    vendor/huawei/h60-common/proprietary/system/etc/gps47531config_cl.xml:system/etc/gps47531config_cl.xml \
    vendor/huawei/h60-common/proprietary/system/etc/thermald.xml:system/etc/thermald.xml \
    vendor/huawei/h60-common/proprietary/system/etc/mogolia_libnfc-nxp.conf:system/etc/mogolia_libnfc-nxp.conf \
    vendor/huawei/h60-common/proprietary/system/etc/camera_orientation.cfg:system/etc/camera_orientation.cfg \
    vendor/huawei/h60-common/proprietary/system/etc/gps.conf:system/etc/gps.conf \
    vendor/huawei/h60-common/proprietary/system/etc/device_state_monitor.conf:system/etc/device_state_monitor.conf \
    vendor/huawei/h60-common/proprietary/system/etc/camera_videosnapshot.cfg:system/etc/camera_videosnapshot.cfg \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_PINE_TLG_ce.xml:system/etc/audio/codec/ascend_PINE_TLG_ce.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_PINE_TLG_normal.xml:system/etc/audio/codec/ascend_PINE_TLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_BELLA_TLGULG_normal.xml:system/etc/audio/codec/ascend_BELLA_TLGULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_BELLA_ULG_normal.xml:system/etc/audio/codec/ascend_BELLA_ULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_PINE_TLGULG_normal.xml:system/etc/audio/codec/ascend_PINE_TLGULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_PINE_CLG_ce.xml:system/etc/audio/codec/ascend_PINE_CLG_ce.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_JAZZ_TLG_normal.xml:system/etc/audio/codec/ascend_JAZZ_TLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_BELLA_CLG_normal.xml:system/etc/audio/codec/ascend_BELLA_CLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_PINE_ULG_normal.xml:system/etc/audio/codec/ascend_PINE_ULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_FIFA_CLG_normal.xml:system/etc/audio/codec/ascend_FIFA_CLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_MOGOLIA_TL_normal.xml:system/etc/audio/codec/ascend_MOGOLIA_TL_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_MOGOLIA_TL_ce.xml:system/etc/audio/codec/ascend_MOGOLIA_TL_ce.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_JAZZ_ULG_normal.xml:system/etc/audio/codec/ascend_JAZZ_ULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_PINE_TLGULG_ce.xml:system/etc/audio/codec/ascend_PINE_TLGULG_ce.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_JAZZ_ULG_ce.xml:system/etc/audio/codec/ascend_JAZZ_ULG_ce.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_JAZZ_TLG_ce.xml:system/etc/audio/codec/ascend_JAZZ_TLG_ce.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_JAZZ_ULCA_ce.xml:system/etc/audio/codec/ascend_JAZZ_ULCA_ce.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_MOGOLIA_ULG_ce.xml:system/etc/audio/codec/ascend_MOGOLIA_ULG_ce.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_JAZZ_ULCA_normal.xml:system/etc/audio/codec/ascend_JAZZ_ULCA_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_JAZZ_SGLTEU_normal.xml:system/etc/audio/codec/ascend_JAZZ_SGLTEU_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_JAZZ_CLG_ce.xml:system/etc/audio/codec/ascend_JAZZ_CLG_ce.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_BELLA_ULG_ce.xml:system/etc/audio/codec/ascend_BELLA_ULG_ce.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_PINE_ULG_ce.xml:system/etc/audio/codec/ascend_PINE_ULG_ce.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_default_normal.xml:system/etc/audio/codec/ascend_default_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_BELLA_TLGULG_ce.xml:system/etc/audio/codec/ascend_BELLA_TLGULG_ce.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_JAZZ_SGLTEU_ce.xml:system/etc/audio/codec/ascend_JAZZ_SGLTEU_ce.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_PINE_CLG_normal.xml:system/etc/audio/codec/ascend_PINE_CLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_BELLA_CLG_ce.xml:system/etc/audio/codec/ascend_BELLA_CLG_ce.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_MOGOLIA_ULCA_ce.xml:system/etc/audio/codec/ascend_MOGOLIA_ULCA_ce.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_JAZZ_CLG_normal.xml:system/etc/audio/codec/ascend_JAZZ_CLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_MOGOLIA_ULCA_normal.xml:system/etc/audio/codec/ascend_MOGOLIA_ULCA_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_MOGOLIA_ULG_normal.xml:system/etc/audio/codec/ascend_MOGOLIA_ULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/codec/ascend_FIFA_CLG_ce.xml:system/etc/audio/codec/ascend_FIFA_CLG_ce.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/algorithm/algorithm_default_normal.xml:system/etc/audio/algorithm/algorithm_default_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/algorithm/algorithm_BELLA_TLGULG_normal.xml:system/etc/audio/algorithm/algorithm_BELLA_TLGULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/algorithm/algorithm_MOGOLIA_TL_normal.xml:system/etc/audio/algorithm/algorithm_MOGOLIA_TL_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/algorithm/algorithm_BELLA_ULG_normal.xml:system/etc/audio/algorithm/algorithm_BELLA_ULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/algorithm/algorithm_MOGOLIA_ULG_normal.xml:system/etc/audio/algorithm/algorithm_MOGOLIA_ULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/algorithm/algorithm_JAZZ_CLG_normal.xml:system/etc/audio/algorithm/algorithm_JAZZ_CLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/algorithm/algorithm_JAZZ_TLG_normal.xml:system/etc/audio/algorithm/algorithm_JAZZ_TLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/algorithm/algorithm_BELLA_CLG_normal.xml:system/etc/audio/algorithm/algorithm_BELLA_CLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/algorithm/algorithm_JAZZ_SGLTEU_normal.xml:system/etc/audio/algorithm/algorithm_JAZZ_SGLTEU_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/algorithm/algorithm_JAZZ_ULCA_normal.xml:system/etc/audio/algorithm/algorithm_JAZZ_ULCA_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/algorithm/algorithm_PINE_CLG_normal.xml:system/etc/audio/algorithm/algorithm_PINE_CLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/algorithm/algorithm_FIFA_CLG_normal.xml:system/etc/audio/algorithm/algorithm_FIFA_CLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/algorithm/algorithm_PINE_ULG_normal.xml:system/etc/audio/algorithm/algorithm_PINE_ULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/algorithm/algorithm_PINE_TLGULG_normal.xml:system/etc/audio/algorithm/algorithm_PINE_TLGULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/algorithm/algorithm_JAZZ_ULG_normal.xml:system/etc/audio/algorithm/algorithm_JAZZ_ULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/algorithm/algorithm_PINE_TLG_normal.xml:system/etc/audio/algorithm/algorithm_PINE_TLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/algorithm/algorithm_MOGOLIA_ULCA_normal.xml:system/etc/audio/algorithm/algorithm_MOGOLIA_ULCA_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/ringtone/ringtone.preset:system/etc/audio/tfa9887/BELLA_TLGULG/normal/ringtone/ringtone.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/ringtone/ringtone.eq:system/etc/audio/tfa9887/BELLA_TLGULG/normal/ringtone/ringtone.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/bypass/bypass.preset:system/etc/audio/tfa9887/BELLA_TLGULG/normal/bypass/bypass.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/bypass/bypass.eq:system/etc/audio/tfa9887/BELLA_TLGULG/normal/bypass/bypass.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/incall_wb/incall_wb.preset:system/etc/audio/tfa9887/BELLA_TLGULG/normal/incall_wb/incall_wb.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/incall_wb/incall_wb.eq:system/etc/audio/tfa9887/BELLA_TLGULG/normal/incall_wb/incall_wb.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/fm/fm.preset:system/etc/audio/tfa9887/BELLA_TLGULG/normal/fm/fm.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/fm/fm.eq:system/etc/audio/tfa9887/BELLA_TLGULG/normal/fm/fm.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/ringtone_hs_spk/ringtone_hs_spk.preset:system/etc/audio/tfa9887/BELLA_TLGULG/normal/ringtone_hs_spk/ringtone_hs_spk.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/ringtone_hs_spk/ringtone_hs_spk.eq:system/etc/audio/tfa9887/BELLA_TLGULG/normal/ringtone_hs_spk/ringtone_hs_spk.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/incall_nb/incall_nb.preset:system/etc/audio/tfa9887/BELLA_TLGULG/normal/incall_nb/incall_nb.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/incall_nb/incall_nb.eq:system/etc/audio/tfa9887/BELLA_TLGULG/normal/incall_nb/incall_nb.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/voip/voip.eq:system/etc/audio/tfa9887/BELLA_TLGULG/normal/voip/voip.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/voip/voip.preset:system/etc/audio/tfa9887/BELLA_TLGULG/normal/voip/voip.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/music/music.preset:system/etc/audio/tfa9887/BELLA_TLGULG/normal/music/music.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/normal/music/music.eq:system/etc/audio/tfa9887/BELLA_TLGULG/normal/music/music.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/speaker_model.speaker:system/etc/audio/tfa9887/BELLA_TLGULG/speaker_model.speaker \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/dsp_coefficient.config:system/etc/audio/tfa9887/BELLA_TLGULG/dsp_coefficient.config \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/ringtone/ringtone.preset:system/etc/audio/tfa9887/BELLA_TLGULG/ce/ringtone/ringtone.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/ringtone/ringtone.eq:system/etc/audio/tfa9887/BELLA_TLGULG/ce/ringtone/ringtone.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/bypass/bypass.preset:system/etc/audio/tfa9887/BELLA_TLGULG/ce/bypass/bypass.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/bypass/bypass.eq:system/etc/audio/tfa9887/BELLA_TLGULG/ce/bypass/bypass.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/incall_wb/incall_wb.preset:system/etc/audio/tfa9887/BELLA_TLGULG/ce/incall_wb/incall_wb.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/incall_wb/incall_wb.eq:system/etc/audio/tfa9887/BELLA_TLGULG/ce/incall_wb/incall_wb.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/fm/fm.preset:system/etc/audio/tfa9887/BELLA_TLGULG/ce/fm/fm.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/fm/fm.eq:system/etc/audio/tfa9887/BELLA_TLGULG/ce/fm/fm.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/ringtone_hs_spk/ringtone_hs_spk.preset:system/etc/audio/tfa9887/BELLA_TLGULG/ce/ringtone_hs_spk/ringtone_hs_spk.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/ringtone_hs_spk/ringtone_hs_spk.eq:system/etc/audio/tfa9887/BELLA_TLGULG/ce/ringtone_hs_spk/ringtone_hs_spk.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/incall_nb/incall_nb.preset:system/etc/audio/tfa9887/BELLA_TLGULG/ce/incall_nb/incall_nb.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/incall_nb/incall_nb.eq:system/etc/audio/tfa9887/BELLA_TLGULG/ce/incall_nb/incall_nb.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/voip/voip.eq:system/etc/audio/tfa9887/BELLA_TLGULG/ce/voip/voip.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/voip/voip.preset:system/etc/audio/tfa9887/BELLA_TLGULG/ce/voip/voip.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/music/music.preset:system/etc/audio/tfa9887/BELLA_TLGULG/ce/music/music.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_TLGULG/ce/music/music.eq:system/etc/audio/tfa9887/BELLA_TLGULG/ce/music/music.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/tfa9887_firmware.patch:system/etc/audio/tfa9887/tfa9887_firmware.patch \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/coldboot.patch:system/etc/audio/tfa9887/coldboot.patch \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/normal/ringtone/ringtone.preset:system/etc/audio/tfa9887/default/normal/ringtone/ringtone.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/normal/ringtone/ringtone.eq:system/etc/audio/tfa9887/default/normal/ringtone/ringtone.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/normal/bypass/bypass.preset:system/etc/audio/tfa9887/default/normal/bypass/bypass.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/normal/bypass/bypass.eq:system/etc/audio/tfa9887/default/normal/bypass/bypass.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/normal/incall_wb/incall_wb.preset:system/etc/audio/tfa9887/default/normal/incall_wb/incall_wb.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/normal/incall_wb/incall_wb.eq:system/etc/audio/tfa9887/default/normal/incall_wb/incall_wb.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/normal/fm/fm.preset:system/etc/audio/tfa9887/default/normal/fm/fm.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/normal/fm/fm.eq:system/etc/audio/tfa9887/default/normal/fm/fm.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/normal/ringtone_hs_spk/ringtone_hs_spk.preset:system/etc/audio/tfa9887/default/normal/ringtone_hs_spk/ringtone_hs_spk.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/normal/ringtone_hs_spk/ringtone_hs_spk.eq:system/etc/audio/tfa9887/default/normal/ringtone_hs_spk/ringtone_hs_spk.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/normal/incall_nb/incall_nb.preset:system/etc/audio/tfa9887/default/normal/incall_nb/incall_nb.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/normal/incall_nb/incall_nb.eq:system/etc/audio/tfa9887/default/normal/incall_nb/incall_nb.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/normal/voip/voip.eq:system/etc/audio/tfa9887/default/normal/voip/voip.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/normal/voip/voip.preset:system/etc/audio/tfa9887/default/normal/voip/voip.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/normal/music/music.preset:system/etc/audio/tfa9887/default/normal/music/music.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/normal/music/music.eq:system/etc/audio/tfa9887/default/normal/music/music.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/speaker_model.speaker:system/etc/audio/tfa9887/default/speaker_model.speaker \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/dsp_coefficient.config:system/etc/audio/tfa9887/default/dsp_coefficient.config \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/ce/ringtone/ringtone.preset:system/etc/audio/tfa9887/default/ce/ringtone/ringtone.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/ce/ringtone/ringtone.eq:system/etc/audio/tfa9887/default/ce/ringtone/ringtone.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/ce/bypass/bypass.preset:system/etc/audio/tfa9887/default/ce/bypass/bypass.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/ce/bypass/bypass.eq:system/etc/audio/tfa9887/default/ce/bypass/bypass.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/ce/incall_wb/incall_wb.preset:system/etc/audio/tfa9887/default/ce/incall_wb/incall_wb.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/ce/incall_wb/incall_wb.eq:system/etc/audio/tfa9887/default/ce/incall_wb/incall_wb.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/ce/fm/fm.preset:system/etc/audio/tfa9887/default/ce/fm/fm.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/ce/fm/fm.eq:system/etc/audio/tfa9887/default/ce/fm/fm.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/ce/ringtone_hs_spk/ringtone_hs_spk.preset:system/etc/audio/tfa9887/default/ce/ringtone_hs_spk/ringtone_hs_spk.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/ce/ringtone_hs_spk/ringtone_hs_spk.eq:system/etc/audio/tfa9887/default/ce/ringtone_hs_spk/ringtone_hs_spk.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/ce/incall_nb/incall_nb.preset:system/etc/audio/tfa9887/default/ce/incall_nb/incall_nb.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/ce/incall_nb/incall_nb.eq:system/etc/audio/tfa9887/default/ce/incall_nb/incall_nb.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/ce/voip/voip.eq:system/etc/audio/tfa9887/default/ce/voip/voip.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/ce/voip/voip.preset:system/etc/audio/tfa9887/default/ce/voip/voip.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/ce/music/music.preset:system/etc/audio/tfa9887/default/ce/music/music.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/default/ce/music/music.eq:system/etc/audio/tfa9887/default/ce/music/music.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/tfa9887_feature.config:system/etc/audio/tfa9887/tfa9887_feature.config \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/ringtone/ringtone.preset:system/etc/audio/tfa9887/BELLA_ULG/normal/ringtone/ringtone.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/ringtone/ringtone.eq:system/etc/audio/tfa9887/BELLA_ULG/normal/ringtone/ringtone.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/bypass/bypass.preset:system/etc/audio/tfa9887/BELLA_ULG/normal/bypass/bypass.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/bypass/bypass.eq:system/etc/audio/tfa9887/BELLA_ULG/normal/bypass/bypass.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/incall_wb/incall_wb.preset:system/etc/audio/tfa9887/BELLA_ULG/normal/incall_wb/incall_wb.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/incall_wb/incall_wb.eq:system/etc/audio/tfa9887/BELLA_ULG/normal/incall_wb/incall_wb.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/fm/fm.preset:system/etc/audio/tfa9887/BELLA_ULG/normal/fm/fm.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/fm/fm.eq:system/etc/audio/tfa9887/BELLA_ULG/normal/fm/fm.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/ringtone_hs_spk/ringtone_hs_spk.preset:system/etc/audio/tfa9887/BELLA_ULG/normal/ringtone_hs_spk/ringtone_hs_spk.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/ringtone_hs_spk/ringtone_hs_spk.eq:system/etc/audio/tfa9887/BELLA_ULG/normal/ringtone_hs_spk/ringtone_hs_spk.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/incall_nb/incall_nb.preset:system/etc/audio/tfa9887/BELLA_ULG/normal/incall_nb/incall_nb.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/incall_nb/incall_nb.eq:system/etc/audio/tfa9887/BELLA_ULG/normal/incall_nb/incall_nb.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/voip/voip.eq:system/etc/audio/tfa9887/BELLA_ULG/normal/voip/voip.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/voip/voip.preset:system/etc/audio/tfa9887/BELLA_ULG/normal/voip/voip.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/music/music.preset:system/etc/audio/tfa9887/BELLA_ULG/normal/music/music.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/normal/music/music.eq:system/etc/audio/tfa9887/BELLA_ULG/normal/music/music.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/speaker_model.speaker:system/etc/audio/tfa9887/BELLA_ULG/speaker_model.speaker \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/dsp_coefficient.config:system/etc/audio/tfa9887/BELLA_ULG/dsp_coefficient.config \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/ringtone/ringtone.preset:system/etc/audio/tfa9887/BELLA_ULG/ce/ringtone/ringtone.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/ringtone/ringtone.eq:system/etc/audio/tfa9887/BELLA_ULG/ce/ringtone/ringtone.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/bypass/bypass.preset:system/etc/audio/tfa9887/BELLA_ULG/ce/bypass/bypass.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/bypass/bypass.eq:system/etc/audio/tfa9887/BELLA_ULG/ce/bypass/bypass.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/incall_wb/incall_wb.preset:system/etc/audio/tfa9887/BELLA_ULG/ce/incall_wb/incall_wb.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/incall_wb/incall_wb.eq:system/etc/audio/tfa9887/BELLA_ULG/ce/incall_wb/incall_wb.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/fm/fm.preset:system/etc/audio/tfa9887/BELLA_ULG/ce/fm/fm.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/fm/fm.eq:system/etc/audio/tfa9887/BELLA_ULG/ce/fm/fm.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/ringtone_hs_spk/ringtone_hs_spk.preset:system/etc/audio/tfa9887/BELLA_ULG/ce/ringtone_hs_spk/ringtone_hs_spk.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/ringtone_hs_spk/ringtone_hs_spk.eq:system/etc/audio/tfa9887/BELLA_ULG/ce/ringtone_hs_spk/ringtone_hs_spk.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/incall_nb/incall_nb.preset:system/etc/audio/tfa9887/BELLA_ULG/ce/incall_nb/incall_nb.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/incall_nb/incall_nb.eq:system/etc/audio/tfa9887/BELLA_ULG/ce/incall_nb/incall_nb.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/voip/voip.eq:system/etc/audio/tfa9887/BELLA_ULG/ce/voip/voip.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/voip/voip.preset:system/etc/audio/tfa9887/BELLA_ULG/ce/voip/voip.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/music/music.preset:system/etc/audio/tfa9887/BELLA_ULG/ce/music/music.preset \
    vendor/huawei/h60-common/proprietary/system/etc/audio/tfa9887/BELLA_ULG/ce/music/music.eq:system/etc/audio/tfa9887/BELLA_ULG/ce/music/music.eq \
    vendor/huawei/h60-common/proprietary/system/etc/audio/dts/ascend_dts_algo_PINE_TLGULG_normal.xml:system/etc/audio/dts/ascend_dts_algo_PINE_TLGULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/dts/ascend_dts_algo_BELLA_TLGULG_normal.xml:system/etc/audio/dts/ascend_dts_algo_BELLA_TLGULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/dts/ascend_dts_algo_BELLA_ULG_normal.xml:system/etc/audio/dts/ascend_dts_algo_BELLA_ULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/dts/ascend_dts_algo_JAZZ_SGLTEU_normal.xml:system/etc/audio/dts/ascend_dts_algo_JAZZ_SGLTEU_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/dts/ascend_dts_algo_JAZZ_ULG_normal.xml:system/etc/audio/dts/ascend_dts_algo_JAZZ_ULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/dts/ascend_dts_algo_JAZZ_CLG_normal.xml:system/etc/audio/dts/ascend_dts_algo_JAZZ_CLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/dts/ascend_dts_algo_MOGOLIA_ULCA_normal.xml:system/etc/audio/dts/ascend_dts_algo_MOGOLIA_ULCA_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/dts/ascend_dts_algo_PINE_ULG_normal.xml:system/etc/audio/dts/ascend_dts_algo_PINE_ULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/dts/ascend_dts_algo_JAZZ_ULCA_normal.xml:system/etc/audio/dts/ascend_dts_algo_JAZZ_ULCA_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/dts/ascend_dts_algo_BELLA_CLG_normal.xml:system/etc/audio/dts/ascend_dts_algo_BELLA_CLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/dts/ascend_dts_algo_MOGOLIA_TL_normal.xml:system/etc/audio/dts/ascend_dts_algo_MOGOLIA_TL_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/dts/ascend_dts_algo_JAZZ_TLG_normal.xml:system/etc/audio/dts/ascend_dts_algo_JAZZ_TLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/dts/ascend_dts_algo_MOGOLIA_ULG_normal.xml:system/etc/audio/dts/ascend_dts_algo_MOGOLIA_ULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/dts/ascend_dts_algo_PINE_TLG_normal.xml:system/etc/audio/dts/ascend_dts_algo_PINE_TLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/dts/ascend_dts_algo_PINE_CLG_normal.xml:system/etc/audio/dts/ascend_dts_algo_PINE_CLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/dts/ascend_dts_algo_default_normal.xml:system/etc/audio/dts/ascend_dts_algo_default_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/mbdrc/ascend_mbdrc_algo_BELLA_TLGULG_normal.xml:system/etc/audio/mbdrc/ascend_mbdrc_algo_BELLA_TLGULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/mbdrc/ascend_mbdrc_algo_PINE_TLGULG_normal.xml:system/etc/audio/mbdrc/ascend_mbdrc_algo_PINE_TLGULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/mbdrc/ascend_mbdrc_algo_BELLA_CLG_normal.xml:system/etc/audio/mbdrc/ascend_mbdrc_algo_BELLA_CLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/mbdrc/ascend_mbdrc_algo_JAZZ_SGLTEU_normal.xml:system/etc/audio/mbdrc/ascend_mbdrc_algo_JAZZ_SGLTEU_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/mbdrc/ascend_mbdrc_algo_JAZZ_TLG_normal.xml:system/etc/audio/mbdrc/ascend_mbdrc_algo_JAZZ_TLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/mbdrc/ascend_mbdrc_algo_JAZZ_ULCA_normal.xml:system/etc/audio/mbdrc/ascend_mbdrc_algo_JAZZ_ULCA_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/mbdrc/ascend_mbdrc_algo_JAZZ_ULG_normal.xml:system/etc/audio/mbdrc/ascend_mbdrc_algo_JAZZ_ULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/mbdrc/ascend_mbdrc_algo_JAZZ_CLG_normal.xml:system/etc/audio/mbdrc/ascend_mbdrc_algo_JAZZ_CLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/mbdrc/ascend_mbdrc_algo_default_normal.xml:system/etc/audio/mbdrc/ascend_mbdrc_algo_default_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/mbdrc/ascend_mbdrc_algo_PINE_TLG_normal.xml:system/etc/audio/mbdrc/ascend_mbdrc_algo_PINE_TLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/mbdrc/ascend_mbdrc_algo_MOGOLIA_ULG_normal.xml:system/etc/audio/mbdrc/ascend_mbdrc_algo_MOGOLIA_ULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/mbdrc/ascend_mbdrc_algo_MOGOLIA_TL_normal.xml:system/etc/audio/mbdrc/ascend_mbdrc_algo_MOGOLIA_TL_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/mbdrc/ascend_mbdrc_algo_MOGOLIA_ULCA_normal.xml:system/etc/audio/mbdrc/ascend_mbdrc_algo_MOGOLIA_ULCA_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/mbdrc/ascend_mbdrc_algo_BELLA_ULG_normal.xml:system/etc/audio/mbdrc/ascend_mbdrc_algo_BELLA_ULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/mbdrc/ascend_mbdrc_algo_PINE_CLG_normal.xml:system/etc/audio/mbdrc/ascend_mbdrc_algo_PINE_CLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/mbdrc/ascend_mbdrc_algo_PINE_ULG_normal.xml:system/etc/audio/mbdrc/ascend_mbdrc_algo_PINE_ULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/modem/ascend_modem_algo_PINE_TLG_normal.xml:system/etc/audio/modem/ascend_modem_algo_PINE_TLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/modem/ascend_modem_algo_PINE_ULG_normal.xml:system/etc/audio/modem/ascend_modem_algo_PINE_ULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/modem/ascend_modem_algo_PINE_TLGULG_normal.xml:system/etc/audio/modem/ascend_modem_algo_PINE_TLGULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/modem/ascend_modem_algo_MOGOLIA_ULCA_normal.xml:system/etc/audio/modem/ascend_modem_algo_MOGOLIA_ULCA_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/modem/ascend_modem_algo_BELLA_ULG_normal.xml:system/etc/audio/modem/ascend_modem_algo_BELLA_ULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/modem/ascend_modem_algo_JAZZ_ULG_normal.xml:system/etc/audio/modem/ascend_modem_algo_JAZZ_ULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/modem/ascend_modem_algo_default_normal.xml:system/etc/audio/modem/ascend_modem_algo_default_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/modem/ascend_modem_algo_JAZZ_CLG_normal.xml:system/etc/audio/modem/ascend_modem_algo_JAZZ_CLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/modem/ascend_modem_algo_BELLA_CLG_normal.xml:system/etc/audio/modem/ascend_modem_algo_BELLA_CLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/modem/ascend_modem_algo_MOGOLIA_ULG_normal.xml:system/etc/audio/modem/ascend_modem_algo_MOGOLIA_ULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/modem/ascend_modem_algo_PINE_CLG_normal.xml:system/etc/audio/modem/ascend_modem_algo_PINE_CLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/modem/ascend_modem_algo_JAZZ_SGLTEU_normal.xml:system/etc/audio/modem/ascend_modem_algo_JAZZ_SGLTEU_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/modem/ascend_modem_algo_BELLA_TLGULG_normal.xml:system/etc/audio/modem/ascend_modem_algo_BELLA_TLGULG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/modem/ascend_modem_algo_JAZZ_ULCA_normal.xml:system/etc/audio/modem/ascend_modem_algo_JAZZ_ULCA_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/modem/ascend_modem_algo_JAZZ_TLG_normal.xml:system/etc/audio/modem/ascend_modem_algo_JAZZ_TLG_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/audio/modem/ascend_modem_algo_MOGOLIA_TL_normal.xml:system/etc/audio/modem/ascend_modem_algo_MOGOLIA_TL_normal.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/tracking/targettracking.xml:system/etc/camera/tracking/targettracking.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/hwscope/kernel:system/etc/camera/hwscope/kernel \
    vendor/huawei/h60-common/proprietary/system/etc/camera/hwscope/hwsz.xml:system/etc/camera/hwscope/hwsz.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/smartae/sonyimx135_liteon/SmartAE.xml:system/etc/camera/smartae/sonyimx135_liteon/SmartAE.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/smartae/ov5648_foxconn/SmartAE.xml:system/etc/camera/smartae/ov5648_foxconn/SmartAE.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/smartae/s5k4e1gx_sunny/SmartAE.xml:system/etc/camera/smartae/s5k4e1gx_sunny/SmartAE.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/smartae/ov5648_sunny/SmartAE.xml:system/etc/camera/smartae/ov5648_sunny/SmartAE.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/smartae/device.config:system/etc/camera/smartae/device.config \
    vendor/huawei/h60-common/proprietary/system/etc/camera/smartae/s5k4e1ga_foxconn/SmartAE.xml:system/etc/camera/smartae/s5k4e1ga_foxconn/SmartAE.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/smartae/imx214_foxconn/SmartAE.xml:system/etc/camera/smartae/imx214_foxconn/SmartAE.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/smartae/s5k4e1gx_foxconn/SmartAE.xml:system/etc/camera/smartae/s5k4e1gx_foxconn/SmartAE.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/smartae/sonyimx134_liteon/SmartAE.xml:system/etc/camera/smartae/sonyimx134_liteon/SmartAE.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/smartae/sonyimx134_sunny/SmartAE.xml:system/etc/camera/smartae/sonyimx134_sunny/SmartAE.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/smartae/imx214_sunny/SmartAE.xml:system/etc/camera/smartae/imx214_sunny/SmartAE.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/tornado/sonyimx135_liteon/TornadoI.ini:system/etc/camera/tornado/sonyimx135_liteon/TornadoI.ini \
    vendor/huawei/h60-common/proprietary/system/etc/camera/tornado/FoliageModelTOA.model:system/etc/camera/tornado/FoliageModelTOA.model \
    vendor/huawei/h60-common/proprietary/system/etc/camera/tornado/NightModelTOA.model:system/etc/camera/tornado/NightModelTOA.model \
    vendor/huawei/h60-common/proprietary/system/etc/camera/tornado/TornadoI.ini:system/etc/camera/tornado/TornadoI.ini \
    vendor/huawei/h60-common/proprietary/system/etc/camera/tornado/NightMinMaxTOA.txt:system/etc/camera/tornado/NightMinMaxTOA.txt \
    vendor/huawei/h60-common/proprietary/system/etc/camera/tornado/imx214_foxconn/TornadoI.ini:system/etc/camera/tornado/imx214_foxconn/TornadoI.ini \
    vendor/huawei/h60-common/proprietary/system/etc/camera/tornado/sonyimx214_sunny/TornadoI.ini:system/etc/camera/tornado/sonyimx214_sunny/TornadoI.ini \
    vendor/huawei/h60-common/proprietary/system/etc/camera/tornado/SunsetModelTOA.model:system/etc/camera/tornado/SunsetModelTOA.model \
    vendor/huawei/h60-common/proprietary/system/etc/camera/tornado/sonyimx134_liteon/TornadoI.ini:system/etc/camera/tornado/sonyimx134_liteon/TornadoI.ini \
    vendor/huawei/h60-common/proprietary/system/etc/camera/tornado/SunsetMinMaxTOA.txt:system/etc/camera/tornado/SunsetMinMaxTOA.txt \
    vendor/huawei/h60-common/proprietary/system/etc/camera/tornado/sonyimx134_sunny/TornadoI.ini:system/etc/camera/tornado/sonyimx134_sunny/TornadoI.ini \
    vendor/huawei/h60-common/proprietary/system/etc/camera/tornado/FoliageMinMaxTOA.txt:system/etc/camera/tornado/FoliageMinMaxTOA.txt \
    vendor/huawei/h60-common/proprietary/system/etc/camera/tornado/sonyimx214_foxconn/TornadoI.ini:system/etc/camera/tornado/sonyimx214_foxconn/TornadoI.ini \
    vendor/huawei/h60-common/proprietary/system/etc/camera/tornado/imx214_sunny/TornadoI.ini:system/etc/camera/tornado/imx214_sunny/TornadoI.ini \
    vendor/huawei/h60-common/proprietary/system/etc/camera/soft3aconfig/sonyimx135_liteon/soft3Aconfig.xml:system/etc/camera/soft3aconfig/sonyimx135_liteon/soft3Aconfig.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/soft3aconfig/ov5648_foxconn/soft3Aconfig.xml:system/etc/camera/soft3aconfig/ov5648_foxconn/soft3Aconfig.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/soft3aconfig/s5k4e1gx_sunny/soft3Aconfig.xml:system/etc/camera/soft3aconfig/s5k4e1gx_sunny/soft3Aconfig.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/soft3aconfig/device.config:system/etc/camera/soft3aconfig/device.config \
    vendor/huawei/h60-common/proprietary/system/etc/camera/soft3aconfig/s5k4e1ga_foxconn/soft3Aconfig.xml:system/etc/camera/soft3aconfig/s5k4e1ga_foxconn/soft3Aconfig.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/soft3aconfig/imx214_foxconn/soft3Aconfig.xml:system/etc/camera/soft3aconfig/imx214_foxconn/soft3Aconfig.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/soft3aconfig/sonyimx134_liteon/soft3Aconfig.xml:system/etc/camera/soft3aconfig/sonyimx134_liteon/soft3Aconfig.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/soft3aconfig/sonyimx134_sunny/soft3Aconfig.xml:system/etc/camera/soft3aconfig/sonyimx134_sunny/soft3Aconfig.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/soft3aconfig/imx214_sunny/soft3Aconfig.xml:system/etc/camera/soft3aconfig/imx214_sunny/soft3Aconfig.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/bshutter/device.config:system/etc/camera/bshutter/device.config \
    vendor/huawei/h60-common/proprietary/system/etc/camera/bshutter/imx214/info.xml:system/etc/camera/bshutter/imx214/info.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/bshutter/imx214/algo.xml:system/etc/camera/bshutter/imx214/algo.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/bshutter/default/info.xml:system/etc/camera/bshutter/default/info.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/bshutter/default/algo.xml:system/etc/camera/bshutter/default/algo.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/multidenoise/hi542/imgproc.xml:system/etc/camera/multidenoise/hi542/imgproc.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/multidenoise/sonyimx135_liteon/imgproc.xml:system/etc/camera/multidenoise/sonyimx135_liteon/imgproc.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/multidenoise/sonyimx135_liteon/multiframe.xml:system/etc/camera/multidenoise/sonyimx135_liteon/multiframe.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/multidenoise/device.config:system/etc/camera/multidenoise/device.config \
    vendor/huawei/h60-common/proprietary/system/etc/camera/multidenoise/s5k4e1ga_foxconn/imgproc.xml:system/etc/camera/multidenoise/s5k4e1ga_foxconn/imgproc.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/multidenoise/default/imgproc.xml:system/etc/camera/multidenoise/default/imgproc.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/multidenoise/default/multiframe.xml:system/etc/camera/multidenoise/default/multiframe.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/multidenoise/sonyimx134_liteon/imgproc.xml:system/etc/camera/multidenoise/sonyimx134_liteon/imgproc.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/multidenoise/sonyimx134_liteon/multiframe.xml:system/etc/camera/multidenoise/sonyimx134_liteon/multiframe.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/multidenoise/sonyimx134_sunny/imgproc.xml:system/etc/camera/multidenoise/sonyimx134_sunny/imgproc.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/multidenoise/sonyimx134_sunny/multiframe.xml:system/etc/camera/multidenoise/sonyimx134_sunny/multiframe.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/multidenoise/ov8830/imgproc.xml:system/etc/camera/multidenoise/ov8830/imgproc.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/multidenoise/multidenoise.xml:system/etc/camera/multidenoise/multidenoise.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/hi542/imgproc.xml:system/etc/camera/davinci/hi542/imgproc.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/hi542/cm_foliage.dat:system/etc/camera/davinci/hi542/cm_foliage.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/sonyimx135_liteon/cm_foliage_s.dat:system/etc/camera/davinci/sonyimx135_liteon/cm_foliage_s.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/sonyimx135_liteon/cm_sunset.dat:system/etc/camera/davinci/sonyimx135_liteon/cm_sunset.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/sonyimx135_liteon/cm_sky.dat:system/etc/camera/davinci/sonyimx135_liteon/cm_sky.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/sonyimx135_liteon/cm_sky_s.dat:system/etc/camera/davinci/sonyimx135_liteon/cm_sky_s.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/sonyimx135_liteon/cm_normal_s.dat:system/etc/camera/davinci/sonyimx135_liteon/cm_normal_s.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/sonyimx135_liteon/imgproc.xml:system/etc/camera/davinci/sonyimx135_liteon/imgproc.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/sonyimx135_liteon/multiframe.xml:system/etc/camera/davinci/sonyimx135_liteon/multiframe.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/sonyimx135_liteon/cm_normal.dat:system/etc/camera/davinci/sonyimx135_liteon/cm_normal.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/sonyimx135_liteon/cm_foliage.dat:system/etc/camera/davinci/sonyimx135_liteon/cm_foliage.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/ov5648_foxconn/imgproc.xml:system/etc/camera/davinci/ov5648_foxconn/imgproc.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/s5k4e1gx_sunny/imgproc.xml:system/etc/camera/davinci/s5k4e1gx_sunny/imgproc.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/ov5648_sunny/imgproc.xml:system/etc/camera/davinci/ov5648_sunny/imgproc.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/device.config:system/etc/camera/davinci/device.config \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/s5k4e1ga_foxconn/imgproc.xml:system/etc/camera/davinci/s5k4e1ga_foxconn/imgproc.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/s5k4e1ga_foxconn/cm_foliage.dat:system/etc/camera/davinci/s5k4e1ga_foxconn/cm_foliage.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/imx214_foxconn/cm_foliage_s.dat:system/etc/camera/davinci/imx214_foxconn/cm_foliage_s.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/imx214_foxconn/cm_sunset.dat:system/etc/camera/davinci/imx214_foxconn/cm_sunset.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/imx214_foxconn/cm_sky.dat:system/etc/camera/davinci/imx214_foxconn/cm_sky.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/imx214_foxconn/cm_sky_s.dat:system/etc/camera/davinci/imx214_foxconn/cm_sky_s.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/imx214_foxconn/cm_normal_s.dat:system/etc/camera/davinci/imx214_foxconn/cm_normal_s.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/imx214_foxconn/imgproc.xml:system/etc/camera/davinci/imx214_foxconn/imgproc.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/imx214_foxconn/multiframe.xml:system/etc/camera/davinci/imx214_foxconn/multiframe.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/imx214_foxconn/cm_normal.dat:system/etc/camera/davinci/imx214_foxconn/cm_normal.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/imx214_foxconn/cm_foliage.dat:system/etc/camera/davinci/imx214_foxconn/cm_foliage.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/s5k4e1gx_foxconn/imgproc.xml:system/etc/camera/davinci/s5k4e1gx_foxconn/imgproc.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/default/cm_correction.dat:system/etc/camera/davinci/default/cm_correction.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/default/cm_sunset.dat:system/etc/camera/davinci/default/cm_sunset.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/default/cm_sky.dat:system/etc/camera/davinci/default/cm_sky.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/default/imgproc.xml:system/etc/camera/davinci/default/imgproc.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/default/cm_normal.dat:system/etc/camera/davinci/default/cm_normal.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/default/cm_foliage.dat:system/etc/camera/davinci/default/cm_foliage.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/sonyimx134_liteon/cm_foliage_s.dat:system/etc/camera/davinci/sonyimx134_liteon/cm_foliage_s.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/sonyimx134_liteon/cm_sunset.dat:system/etc/camera/davinci/sonyimx134_liteon/cm_sunset.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/sonyimx134_liteon/cm_sky.dat:system/etc/camera/davinci/sonyimx134_liteon/cm_sky.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/sonyimx134_liteon/cm_sky_s.dat:system/etc/camera/davinci/sonyimx134_liteon/cm_sky_s.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/sonyimx134_liteon/cm_normal_s.dat:system/etc/camera/davinci/sonyimx134_liteon/cm_normal_s.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/sonyimx134_liteon/imgproc.xml:system/etc/camera/davinci/sonyimx134_liteon/imgproc.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/sonyimx134_liteon/multiframe.xml:system/etc/camera/davinci/sonyimx134_liteon/multiframe.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/sonyimx134_liteon/cm_normal.dat:system/etc/camera/davinci/sonyimx134_liteon/cm_normal.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/sonyimx134_liteon/cm_foliage.dat:system/etc/camera/davinci/sonyimx134_liteon/cm_foliage.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/davinci/ov8830/imgproc.xml:system/etc/camera/davinci/ov8830/imgproc.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/filter/filter.xml:system/etc/camera/filter/filter.xml \
    vendor/huawei/h60-common/proprietary/system/etc/camera/filter/mixIm.dat:system/etc/camera/filter/mixIm.dat \
    vendor/huawei/h60-common/proprietary/system/etc/camera/meitu/kujiu2.mtdata:system/etc/camera/meitu/kujiu2.mtdata \
    vendor/huawei/h60-common/proprietary/system/etc/camera/meitu/sucai7.mtdata:system/etc/camera/meitu/sucai7.mtdata \
    vendor/huawei/h60-common/proprietary/system/etc/camera/meitu/overlayMap.mtdata:system/etc/camera/meitu/overlayMap.mtdata \
    vendor/huawei/h60-common/proprietary/system/etc/camera/meitu/moran.mtdata:system/etc/camera/meitu/moran.mtdata \
    vendor/huawei/h60-common/proprietary/system/etc/camera/meitu/PSScreen.mtdata:system/etc/camera/meitu/PSScreen.mtdata \
    vendor/huawei/h60-common/proprietary/system/etc/camera/meitu/qingse1.mtdata:system/etc/camera/meitu/qingse1.mtdata \
    vendor/huawei/h60-common/proprietary/system/etc/camera/meitu/kujiu1.mtdata:system/etc/camera/meitu/kujiu1.mtdata \
    vendor/huawei/h60-common/proprietary/system/etc/camera/meitu/kujiu3.mtdata:system/etc/camera/meitu/kujiu3.mtdata \
    vendor/huawei/h60-common/proprietary/system/etc/camera/meitu/chengguang.mtdata:system/etc/camera/meitu/chengguang.mtdata \
    vendor/huawei/h60-common/proprietary/system/etc/camera/meitu/sucai3.mtdata:system/etc/camera/meitu/sucai3.mtdata \
    vendor/huawei/h60-common/proprietary/system/etc/camera/meitu/sucai4.mtdata:system/etc/camera/meitu/sucai4.mtdata \
    vendor/huawei/h60-common/proprietary/system/etc/camera/meitu/kujiu4.mtdata:system/etc/camera/meitu/kujiu4.mtdata \
    vendor/huawei/h60-common/proprietary/system/etc/camera/meitu/dianying.mtdata:system/etc/camera/meitu/dianying.mtdata \
    vendor/huawei/h60-common/proprietary/system/etc/camera/meitu/sucai5.mtdata:system/etc/camera/meitu/sucai5.mtdata \
    vendor/huawei/h60-common/proprietary/system/etc/camera/meitu/kujiu5.mtdata:system/etc/camera/meitu/kujiu5.mtdata \
    vendor/huawei/h60-common/proprietary/system/etc/gps4752.conf:system/etc/gps4752.conf \
    vendor/huawei/h60-common/proprietary/system/etc/clatd.conf:system/etc/clatd.conf \
    vendor/huawei/h60-common/proprietary/system/etc/gps47531config.xml:system/etc/gps47531config.xml \
    vendor/huawei/h60-common/proprietary/system/etc/mogolia_libnfc-brcm.conf:system/etc/mogolia_libnfc-brcm.conf
